---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: true
      
  - name: install tmux
    apt: 
      name: tmux
      state: latest

  - name: install glances
    apt:
      name: glances
      state: latest 
