- name: install apache, Lynx browser
  package: 
      name: 
         - "{{ apache_package_name }}"
         - "{{ php_package_name }}"
         - "{{ lynx_browser_package_name }}"
      state: latest
      update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: start apache2 (this is not required for Ubuntu. But for Fedora and RHEL you need to start services manually after installation in most cases)
  tags: apache, start_service
  service:
       name: "{{ apache_service }}"
       state: started
       enabled: true

- name: change timeout value in apache2.conf
  tags: apache
  lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^Timeout '
      line: Timeout 300
  notify: restart_apache


- name: copy default html file for site
  tags: apache
  copy:
      src: default_site.html 
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

